# Generated by Django 5.0.4 on 2024-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_selfstudy_completed_remove_selfstudy_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfstudy',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfstudy',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
