# Generated by Django 5.0.4 on 2024-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_selfstudy_completed_selfstudy_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudy',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
