# Generated by Django 5.0.4 on 2024-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_friends'),
        ('resources', '0003_domain_id_alter_domain_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='users', to='resources.domain'),
        ),
    ]
