# Generated by Django 5.0.4 on 2024-04-27 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='domains',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domains',
            field=models.CharField(choices=[('Cyber Security', 'Cyber Security'), ('Blockchain', 'Blockchain'), ('Data Science', 'Data Science'), ('AppDev', 'AppDev'), ('AIML', 'AIML'), ('WebDev', 'WebDev')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
