# Generated by Django 5.0.4 on 2024-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_domains_userprofile_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='domains',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domains',
            field=models.ManyToManyField(related_name='user_profiles', to='accounts.domain'),
        ),
    ]
