# Generated by Django 5.0.4 on 2024-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_domain_remove_userprofile_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], default='morning', max_length=10),
        ),
    ]
