# Generated by Django 5.0.4 on 2024-04-28 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
